### ISSUE TITLE
java.nio.file.InvalidPathException on Windows with $ (Trailing char < > at index)

### ISSUE THREAD

**Issue by MrGung** [babashka/babashka#1105] opened 2021-12-14 06:18 UTC
**version**
0.7.0 but also got it with 0.6.8

**platform**

Windows 10

**problem**

I get a 
```
----- Error --------------------------------------------------------------------
Type:     java.nio.file.InvalidPathException
Message:  Trailing char < > at index 39: c:\program files (x86)\microsoft visual
Location: 22:6

----- Stack trace --------------------------------------------------------------
gitlab.clone-or-fetch-individual - d:\Entwicklung\babashka-scripts\src\gitlab\clone_or_fetch_individual.clj:22:5
git.fetch-all-projects-in-dir    - d:\Entwicklung\babashka-scripts\src\git\fetch_all_projects_in_dir.clj:30:9
git.fetch-all-projects-in-dir    - d:\Entwicklung\babashka-scripts\src\git\fetch_all_projects_in_dir.clj:31:5
user                             - <expr>:1:10
```

Line 22 reads:
`@^{:dir full-local-path :out :inherit :err :inherit} ($ git fetch --prune)`

```
>where git
c:\program files\Git\cmd\git.exe
```

I looked into %path% - where there are some "microsoft visual"-entries quite at the beginning (before the path to git...) There are also other entries containing multiple whitespaces in its path before the MS-ones...

**repro**

[ Please provide a minimal working reproduction of the problem ]

**expected behavior**

[ What is the behavior you expected to see? Please provide a minimal working example ]

**Comment by borkdude** [comment] 2021-12-14 11:11
I'm not sure if this is a problem with babashka or just with `ProcessBuilder` and Windows.

Can you try a more minimal repro with 
```
(require '[babashka.process :as p])
(-> (p/process ["git" "status"] {:out :string}) p/check :out)
```
This is pretty much equivalent to:

``` clojure
(require '[clojure.java.io :as io])

(prn (-> (doto (java.lang.ProcessBuilder. ["git" "status"])
      (.redirectOutput (java.lang.ProcessBuilder$Redirect/to (io/file "output.txt"))))
    (.start)
    (.waitFor))) ;; if this doesn't print zero, check the error output stream
(slurp "output.txt")
```

**Comment by MrGung** [comment] 2021-12-14 15:24
Both of your repros work for me.

What now works in my code is:
```
    (-> (doto (java.lang.ProcessBuilder. ["git" "fetch" "--prune"])
          (.directory (io/file full-local-path )))
      (.start)
      (.waitFor))

    (-> (doto (java.lang.ProcessBuilder. ["git" "pull" "--ff-only"])
          (.directory (io/file full-local-path )))
      (.start)
      (.waitFor))
```

`--debug` with the previous version of the code gives:

```
----- Stack trace --------------------------------------------------------------
gitlab.clone-or-fetch-individual - d:\Entwicklung\babashka-scripts\src\gitlab\clone_or_fetch_individual.clj:24:9
gitlab.clone-or-fetch-individual - d:\Entwicklung\babashka-scripts\src\gitlab\clone_or_fetch_individual.clj:24:5
git.fetch-all-projects-in-dir    - d:\Entwicklung\babashka-scripts\src\git\fetch_all_projects_in_dir.clj:30:9
git.fetch-all-projects-in-dir    - d:\Entwicklung\babashka-scripts\src\git\fetch_all_projects_in_dir.clj:31:5
user                             - <expr>:1:10

----- Exception ----------------------------------------------------------------
clojure.lang.ExceptionInfo: Trailing char < > at index 39: c:\program files (x86)\microsoft visual
{:type :sci/error, :line 24, :column 9, :message "Trailing char < > at index 39: c:\\program files (x86)\\microsoft visual ", :sci.impl/callstack #object[clojure.lang.Volatile 0x25798cd1 {:status :ready, :val ({:line 1, :column 10, :file "<expr>", :ns #object[sci.impl.vars.SciNamespace 0x42d992ba "user"]} {:ns #object[sci.impl.vars.SciNamespace 0x5de8c094 "git.fetch-all-projects-in-dir"], :file "d:\\Entwicklung\\babashka-scripts\\src\\git\\fetch_all_projects_in_dir.clj"} {:line 31, :column 5, :ns #object[sci.impl.vars.SciNamespace 0x5de8c094 "git.fetch-all-projects-in-dir"], :file "d:\\Entwicklung\\babashka-scripts\\src\\git\\fetch_all_projects_in_dir.clj", :sci.impl/f-meta {:line 30, :column 9, :sci.impl/op :resolve-sym}} {:line 24, :column 5, :ns #object[sci.impl.vars.SciNamespace 0x3889eea3 "gitlab.clone-or-fetch-individual"], :file "d:\\Entwicklung\\babashka-scripts\\src\\gitlab\\clone_or_fetch_individual.clj", :sci.impl/f-meta {:ns #object[sci.impl.vars.SciNamespace 0x269f2156 "babashka.process"], :name check, :arglists ([proc]), :doc nil}} {:line 24, :column 9, :ns #object[sci.impl.vars.SciNamespace 0x3889eea3 "gitlab.clone-or-fetch-individual"], :file "d:\\Entwicklung\\babashka-scripts\\src\\gitlab\\clone_or_fetch_individual.clj", :sci.impl/f-meta {:ns #object[sci.impl.vars.SciNamespace 0x269f2156 "babashka.process"], :name process, :arglists ([& args]), :doc nil}})}], :file "d:\\Entwicklung\\babashka-scripts\\src\\gitlab\\clone_or_fetch_individual.clj", :locals {title "", local-root nil, full-local-path "d:\\DEV\\git\\ANO_MeineReisen\\ano-client", clone-url nil}}
 at sci.impl.utils$rethrow_with_location_of_node.invokeStatic (utils.cljc:85)
    sci.impl.evaluator$eval.invokeStatic (evaluator.cljc:338)
    sci.impl.analyzer$return_call$fn__8947.invoke (analyzer.cljc:1040)
    sci.impl.evaluator$eval.invokeStatic (evaluator.cljc:341)
    sci.impl.evaluator$eval.invoke (evaluator.cljc:335)
    sci.impl.evaluator$eval_do.invokeStatic (evaluator.cljc:290)
    sci.impl.analyzer$return_do$fn__8011.invoke (analyzer.cljc:115)
    sci.impl.evaluator$eval.invokeStatic (evaluator.cljc:341)
    sci.impl.fns$fun$arity_3__7320.invoke (fns.cljc:153)
```

**Comment by borkdude** [comment] 2021-12-14 17:43
Wait, both of the repros work, so also the `babashka.process/process` call?

**Comment by MrGung** [comment] 2021-12-14 17:57
Yes.

I wondered what could change the execution-context but I have no idea - except I executed your code in a REPL. My code was executed from a cmd-console via `bb -m`.
Tomorrow I will try the other way around.

**Comment by MrGung** [comment] 2021-12-14 18:40
I tried.

Your code can also be executed as a script (either via `-m` or `-f`) on my machine. 
My code (back to the version using `process`) throws the exception when executed via bb - but works via REPL (calling `-main` with the appropriate args).

🤷‍♂️

**Comment by borkdude** [comment] 2021-12-14 19:01
Can you make an actual repro using `babashka.process/process`, step for step, very explicit without any room for ambiguity?

**Comment by bobisageek** [comment] 2021-12-16 19:36
Is it possible that, in the context where the exception occurs, there's an entry in %PATH% that _ends_ with a space? I was able to reproduce the error by putting a space the end of one %path% entry. It also happens (for me) irrespective of the relative positions between the command in question (e.g. 'git') and the trailing-spaced entry in %path%.

**Comment by MrGung** [comment] 2021-12-17 06:06
You are right - there is/was a trailing space at the end of that path-entry. I removed it and am going to test after a clean reboot.

**Comment by bobisageek** [comment] 2021-12-17 16:07
> I don't understand why removing the space removes the problem, though.

There was a recent-ish change to babashka.process which tries to find executables on %path% using `babashka.fs/which`. As part of its work, `which` constructs a `Path` object for entries in %PATH%. The `Path` constructor (on Windows) throws an `InvalidPathException` when the path has a trailing space:

```clj
; happy path
user=> (.toPath (clojure.java.io/file "C:\\stuff"))
#object[sun.nio.fs.WindowsPath 0x1af2921c "C:\\stuff"]

; failure path
user=> (.toPath (clojure.java.io/file "C:\\stuff "))
Trailing char < > at index 8: C:\stuff
user=> *e
#error {
 :cause "Trailing char < > at index 8: C:\\stuff "
 :via
 [{:type java.nio.file.InvalidPathException
   :message "Trailing char < > at index 8: C:\\stuff "
   :at [sun.nio.fs.WindowsPathParser normalize "WindowsPathParser.java" 191]}]
...
```

So, removing the trailing space makes the `Path` constructible.

**Comment by borkdude** [comment] 2021-12-17 22:43
Should we remove trailing spaces from the path automatically when trying to find the executable?

**Comment by MrGung** [comment] 2021-12-18 07:23
I am ambivalent.

It could be fixed by triming, or by catching the exception and augmenting a propable cause. Or no fix of that at all.

My core problem was the stacktrace - I couldn't find the code in babashka that triggered the exception. Could that be improved? Or is it just my reading and understanding?

**Comment by borkdude** [comment] 2021-12-18 12:08
I think it would be reasonable that our `default-program-resolver` in `babashka.process` would not crash, but in case of an exception just returns the original string `git`. Probably this should even be fixed in `babashka.fs/which` which should just return `nil` when there are strange things on the path instead of crashing.

**Comment by MrGung** [comment] 2021-12-18 12:12
I would like to contribute that (even though it is just two lines + tests...)

I would fix it in `which` - by catching the exception. Is any logging of the exception required?

**Comment by borkdude** [comment] 2021-12-18 12:27
@MrGung Interestingly this works on Windows:

```
user=> (java.io.File. "foo ")
#object[java.io.File 0x3cbf1ba4 "foo "]
```

Just not the conversion to a path. We could also leave this as a sign that users should just fix the root cause instead of covering up the error. I'm not really sure now.

**Comment by borkdude** [comment] 2021-12-18 12:29
Alternatively we could just trim the PATH here:

https://github.com/babashka/fs/blob/6019ec9cb09632fdf84e4bc5879fd47ed57a35eb/src/babashka/fs.cljc#L698

**Comment by MrGung** [comment] 2021-12-18 12:29
My take is that I wouldn't fix it in code if the cause were prominent (in the stacktrace).

**Comment by borkdude** [comment] 2021-12-18 12:33
There is a JDK bug report about it here: https://bugs.java.com/bugdatabase/view_bug.do?bug_id=8190546

**Comment by borkdude** [comment] 2021-12-18 13:06
@MrGung OK, the best option is probably to improve the stacktrace.

If we add something like this to `babashka/impl/error_handler.clj`:

```
(defn error-context [ex opts] 1 reference
 (run! prn (map StackTraceElement->vec (.getStackTrace (or (ex-cause ex) ex))))
```

we can see some more interesting bits from the native stacktrace:

```
----- Error --------------------------------------------------------------------
Type:     java.nio.file.InvalidPathException
Message:  Trailing char < > at index 3: git
Location: 1:2

[sun.nio.fs.WindowsPathParser normalize "WindowsPathParser.java" 191]
[sun.nio.fs.WindowsPathParser parse "WindowsPathParser.java" 153]
[sun.nio.fs.WindowsPathParser parse "WindowsPathParser.java" 77]
[sun.nio.fs.WindowsPath parse "WindowsPath.java" 92]
[sun.nio.fs.WindowsFileSystem getPath "WindowsFileSystem.java" 229]
[java.io.File toPath "File.java" 2292]
[babashka.fs$as_path invokeStatic "fs.cljc" 35]
[babashka.fs$as_path invoke "fs.cljc" 32]
[babashka.fs$absolute_QMARK_ invokeStatic "fs.cljc" 101]
[babashka.fs$absolute_QMARK_ invoke "fs.cljc" 99]
[babashka.fs$relative_QMARK_ invokeStatic "fs.cljc" 117]
[babashka.fs$relative_QMARK_ invoke "fs.cljc" 115]
[babashka.process$default_program_resolver invokeStatic "process.cljc" 163]
[babashka.process$default_program_resolver invoke "process.cljc" 162]
[babashka.process$build invokeStatic "process.cljc" 190]
[babashka.process$build invoke "process.cljc" 174]
[babashka.process$process invokeStatic "process.cljc" 247]
[babashka.process$process invoke "process.cljc" 228]
[clojure.lang.AFn applyToHelper "AFn.java" 160]
[clojure.lang.AFn applyTo "AFn.java" 144]
[clojure.core$apply invokeStatic "core.clj" 667]
[clojure.core$apply invoke "core.clj" 662]
[babashka.impl.process$process invokeStatic "process.clj" 12]
[babashka.impl.process$process doInvoke "process.clj" 10]
[clojure.lang.RestFn invoke "RestFn.java" 436]
[sci.impl.vars.SciVar invoke "vars.cljc" 327]
[sci.impl.analyzer$return_call$fn__9794 invoke "analyzer.cljc" 1040]
[sci.impl.evaluator$eval invokeStatic "evaluator.cljc" 341]
[sci.impl.evaluator$eval invoke "evaluator.cljc" 335]
[sci.impl.evaluator$eval_let invokeStatic "evaluator.cljc" 76]
[sci.impl.evaluator$eval_let invoke "evaluator.cljc" 54]
[sci.impl.analyzer$expand_let_STAR_$fn__9441 invoke "analyzer.cljc" 395]
[sci.impl.evaluator$eval invokeStatic "evaluator.cljc" 341]
[sci.impl.evaluator$eval invoke "evaluator.cljc" 335]
[sci.impl.analyzer$return_call$fn__9786 invoke "analyzer.cljc" 1040]
[sci.impl.evaluator$eval invokeStatic "evaluator.cljc" 341]
[sci.impl.evaluator$eval invoke "evaluator.cljc" 335]
[sci.impl.interpreter$eval_form invokeStatic "interpreter.cljc" 45]
[sci.impl.interpreter$eval_form invoke "interpreter.cljc" 27]
[sci.impl.interpreter$eval_string_STAR_ invokeStatic "interpreter.cljc" 61]
[sci.impl.interpreter$eval_string_STAR_ invoke "interpreter.cljc" 54]
[sci.core$eval_string_STAR_ invokeStatic "core.cljc" 240]
[sci.core$eval_string_STAR_ invoke "core.cljc" 236]
[babashka.main$exec$fn__40292$fn__40293 invoke "main.clj" 850]
[babashka.main$exec$fn__40292 invoke "main.clj" 847]
[babashka.main$exec invokeStatic "main.clj" 837]
[babashka.main$exec invoke "main.clj" 672]
[babashka.main$main invokeStatic "main.clj" 921]
[babashka.main$main doInvoke "main.clj" 904]
[clojure.lang.RestFn applyTo "RestFn.java" 137]
[clojure.core$apply invokeStatic "core.clj" 667]
[clojure.core$apply invoke "core.clj" 662]
[babashka.main$_main invokeStatic "main.clj" 957]
[babashka.main$_main doInvoke "main.clj" 943]
[clojure.lang.RestFn applyTo "RestFn.java" 137]
[clojure.lang.Var applyTo "Var.java" 705]
[clojure.core$apply invokeStatic "core.clj" 667]
[clojure.main$main_opt invokeStatic "main.clj" 514]
[clojure.main$main_opt invoke "main.clj" 510]
[clojure.main$main invokeStatic "main.clj" 664]
[clojure.main$main doInvoke "main.clj" 616]
[clojure.lang.RestFn applyTo "RestFn.java" 137]
[clojure.lang.Var applyTo "Var.java" 705]
[clojure.main main "main.java" 40]
----- Stack trace --------------------------------------------------------------
user - c:\Temp\fs_repro.clj:1:1
```

The `sci.impl` and `babashka.main` things aren't so interesting to show, but perhaps with a bit of experimentation we can improve the current stack trace.

**Comment by MrGung** [comment] 2021-12-19 10:08
Just to let you know: I'll keep my hands off that change.

**Comment by borkdude** [comment] 2021-12-19 10:18
@MrGung Alright, I'll see what I can do :)

**Comment by borkdude** [comment] 2021-12-19 20:18
@MrGung @bobisageek Hey! I added a little bit of "native" stacktrace to the output:

``` 
C:\Users\borkdude\dev\babashka>deps -M:babashka/dev -e "(babashka.process/process [""""git """"])"
----- Error --------------------------------------------------------------------
Type:     java.nio.file.InvalidPathException
Message:  Trailing char < > at index 3: git
Location: <expr>:1:1

----- Context ------------------------------------------------------------------
1: (babashka.process/process ["git "])
   ^--- Trailing char < > at index 3: git

----- Stack trace --------------------------------------------------------------
babashka.fs/as-path                       - <built-in>
babashka.fs/as-path                       - <built-in>
babashka.fs/absolute?                     - <built-in>
babashka.fs/absolute?                     - <built-in>
babashka.fs/relative?                     - <built-in>
...
clojure.core/apply                        - <built-in>
clojure.core/apply                        - <built-in>
babashka.impl.process/process             - <built-in>
babashka.impl.process/process             - <built-in>
user                                      - <expr>:1:1
```

Feedback welcome. This is in branch `better-stacktrace`. You can run babashka as a JVM dependency like I did above using a deps.edn alias, or download the binary from here: https://ci.appveyor.com/api/buildjobs/riwyjpcw3v1096m0/artifacts/babashka-0.7.1-SNAPSHOT-windows-amd64.zip
Or of course, build it yourself.

**Comment by MrGung** [comment] 2021-12-20 06:19
Now I get for my case

```
----- Error --------------------------------------------------------------------
Type:     java.nio.file.InvalidPathException
Message:  Trailing char < > at index 36: D:\Users\T06057A\AppData\Roaming\npm
Location: 24:6

----- Stack trace --------------------------------------------------------------
babashka.fs/as-path                           - <built-in>
babashka.fs/path                              - <built-in>
babashka.fs/path                              - <built-in>
clojure.core/mapv/fn--8482                    - <built-in>
clojure.core.protocols/fn--8198               - <built-in>
...
gitlab.clone-or-fetch-individual              - d:\Entwicklung\babashka-scripts\src\gitlab\clone_or_fetch_individual.clj:24:5
git.fetch-all-projects-in-dir/apply           - d:\Entwicklung\babashka-scripts\src\git\fetch_all_projects_in_dir.clj:21:13
```

Me would still not conclude that it's something about my PATH (from the stacktrace). I would now expect `fs/which` to appear in the trace!?

**Comment by borkdude** [comment] 2021-12-20 08:34
Yes, `fs/which` would appear in the place of the dots, but there is a maximum of stack trace elements shown. Perhaps try the newest from the branch where I added a `dedupe`.

**Comment by borkdude** [comment] 2021-12-20 09:56
@MrGung Try again with `bb --debug ...`, it should show the entire stacktrace.

**Comment by MrGung** [comment] 2021-12-21 06:58
Do I need a new build?
I'm still getting the ellipsis with `--debug`:

```
>bb --debug -m git.fetch-all-projects-in-dir d:\DEV\git\ANO_MeineReisen
Starting in d:\DEV\git\ANO_MeineReisen
fetching d:\DEV\git\ANO_MeineReisen\ano-client
pulling ff-only -> d:\DEV\git\ANO_MeineReisen\ano-client
----- Error --------------------------------------------------------------------
Type:     java.nio.file.InvalidPathException
Message:  Trailing char < > at index 36: D:\Users\T06057A\AppData\Roaming\npm
Location: 24:6

----- Locals -------------------------------------------------------------------
title:           ""
local-root:      nil
full-local-path: "d:\\DEV\\git\\ANO_MeineReisen\\ano-client"
clone-url:       nil

----- Stack trace --------------------------------------------------------------
babashka.fs/as-path                           - <built-in>
babashka.fs/path                              - <built-in>
babashka.fs/path                              - <built-in>
clojure.core/mapv/fn--8482                    - <built-in>
clojure.core.protocols/fn--8198               - <built-in>
...
gitlab.clone-or-fetch-individual              - d:\Entwicklung\babashka-scripts\src\gitlab\clone_or_fetch_individual.clj:24:5
```

**Comment by borkdude** [comment] 2021-12-21 09:45
@MrGung Fixed on the branch

**Comment by MrGung** [comment] 2021-12-21 11:47
Is the link to the binary still valid? I re-downloaded but the trace did not change at all.

**Comment by borkdude** [comment] 2021-12-21 11:59
The link to the binary points to the old binary, I didn't change that. Here is the new one, but you can find it yourself too here:

https://ci.appveyor.com/project/borkdude/babashka/history

https://ci.appveyor.com/api/buildjobs/4emgdxj4knl91l4q/artifacts/babashka-0.7.1-SNAPSHOT-windows-amd64.zip

**Comment by borkdude** [comment] 2021-12-21 22:01
Btw, the new babashka stacktrace shows that it doesn't fail in `fs/which` but in `fs/relative?` which is called before `fs/which`:

```
babashka.fs/as-path                       - <built-in>
babashka.fs/absolute?                     - <built-in>
babashka.fs/relative?                     - <built-in>
babashka.process/default-program-resolver - <built-in>
babashka.process/build                    - <built-in>
babashka.process/process                  - <built-in>
clojure.core/apply                        - <built-in>
babashka.impl.process/process             - <built-in>
user                                      - C:\Temp\prog.clj:1:2
user                                      - C:\Temp\prog.clj:1:1
```

**Comment by borkdude** [comment] 2021-12-21 22:01
On this line: https://github.com/babashka/process/blob/7847bdd56bb8db3293070a5c09b94dddc77c0155/src/babashka/process.cljc#L163

**Comment by MrGung** [comment] 2021-12-22 05:34
Here is mine:

```
----- Stack trace --------------------------------------------------------------
babashka.fs/as-path                           - <built-in>
babashka.fs/path                              - <built-in>
clojure.core/mapv/fn--8482                    - <built-in>
clojure.core.protocols/fn--8198               - <built-in>
clojure.core.protocols/fn--8153/G--8148--8162 - <built-in>
clojure.core.protocols/seq-reduce             - <built-in>
clojure.core.protocols/fn--8175               - <built-in>
clojure.core.protocols/fn--8127/G--8122--8140 - <built-in>
clojure.core/reduce                           - <built-in>
clojure.core/mapv                             - <built-in>
babashka.fs/split-paths                       - <built-in>
babashka.fs/exec-paths                        - <built-in>
babashka.fs/which                             - <built-in>
babashka.process/default-program-resolver     - <built-in>
babashka.process/build                        - <built-in>
babashka.process/process                      - <built-in>
clojure.core/apply                            - <built-in>
babashka.impl.process/process                 - <built-in>
gitlab.clone-or-fetch-individual              - d:\Entwicklung\babashka-scripts\src\gitlab\clone_or_fetch_individual.clj:24:5
```

This stacktrace would definitely help. Alas, it's not `relative?` that crashes for me...

**Comment by borkdude** [comment] 2021-12-22 11:14
I've decided that `babashka.process/default-program-resolver` should never throw but just return the original argument. It's meant to be helpful, not to introduce behavior that wasn't there before. I'll also include the new stacktrace stuff. Just have to adapt the tests for that now.

**Closed** 2021-12-22 12:04 UTC
