### ISSUE TITLE
Error messages are sometimes missing context info

### ISSUE THREAD

**Issue by krajj7** [babashka/babashka#1232] opened 2022-04-05 12:15 UTC
I have encountered some strangely unhelpful error messages / stacktraces from babashka in some cases.

This is a minimal script to demonstrate:

```clj
#!/usr/bin/env bb
(ns my)

(defn myfn []
  (assert false))

(binding []
  (myfn)
  (try 1 (catch Throwable e)))
```

When I run this with babashka v0.8.0 I get this output with no context or location info:
```
----- Error --------------------------------------------------------------------
Type:     java.lang.AssertionError
Message:  Assert failed: false
```

When either the empty binding is removed (unwrapped), or the try-catch is removed, the resulting error message is much better:
```
----- Error --------------------------------------------------------------------
Type:     java.lang.AssertionError
Message:  Assert failed: false
Location: /home/jan/clj/automove/./errtest.bb:8:3

----- Context ------------------------------------------------------------------
4: (defn myfn []
5:   (assert false))
6: 
7: (binding []
8:   (myfn)
     ^--- Assert failed: false
9:   )

----- Stack trace --------------------------------------------------------------
my/myfn - /home/jan/clj/automove/./errtest.bb:4:1
my      - /home/jan/clj/automove/./errtest.bb:8:3
```

It would be great if the original script also gave this info.

**Comment by bobisageek** [comment] 2022-04-10 05:45
I don't have a root cause, but I'm posting what I've found so far in case it helps.

The proximate cause of the limited output appears to be that the exception that babashka catches is not a `:sci/error`. The stacktraces felt like they could maybe be boiled down a bit. Since `binding` is a macro that expands to (within other things) a `try`, and the `assert` is essentially throwing an exception, I tried 'shrinking' to a slightly simpler repro.

```shell
$ bb '(try (throw (Exception. "hi")))'
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  hi
Location: <expr>:1:6

----- Context ------------------------------------------------------------------
1: (try (throw (Exception. "hi")))
        ^--- hi

versus

$ bb '(try 1 (throw (Exception. "hi")))'
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  hi
```

This removes a couple stack frames. My working theory at the moment is that the difference in behavior has to do with when the try has more than one expression in the body. My wild speculation is that it might have to do with `return-do` returning a `Node` when the do block has more than one item, but not when there's one (at the moment, that's correlation with no strong evidence of causation).

**Comment by bobisageek** [comment] 2022-04-12 00:29
If I'm reading and interpreting everything correctly, what's happening is that the try body is being wrapped in a `do`:
https://github.com/babashka/sci/blob/64545c0f254d25c872086a17afa604ac802b5ee1/src/sci/impl/analyzer.cljc#L734

In the "working" examples (only a `throw` or a call to `myfn` in the body of the `try`), the `do` contains only one form. When those `do`s are analyzed, the return value from `return-do` is the analyzed body, which would come from `analyze-throw` or `analyze-call`, both of which return nodes with stack values, and when the unhandled (in user code) exception is handled via the rethrow function from `eval-try`, there is a stack that can be used to build the wrapping sci error.

In the "non-working" examples (with more than one call in the do), `return-do` ends up returning a node with a nil stack, and when we end up in the rethrow function, there's a nil stack on the node, and there's no callstack in the dereffed env, so we fall through to throwing the original exception.

**Comment by borkdude** [comment] 2022-04-12 08:25
The general way of solving these issues is to push something in the stack value, correct.

**Comment by bobisageek** [comment] 2022-04-16 20:56
With adding stacks to `let*` and `try`, we can get some context for the example expressions:

```shell
$ ./bb '(binding [] 1 (assert false))'
----- Error --------------------------------------------------------------------
Type:     java.lang.AssertionError
Message:  Assert failed: false
Location: <expr>:1:1

----- Context ------------------------------------------------------------------
1: (binding [] 1 (assert false))
   ^--- Assert failed: false
```
```shell
$ ./bb '(try 1 (throw (Exception. "hi")))'
----- Error --------------------------------------------------------------------
Type:     java.lang.Exception
Message:  hi
Location: <expr>:1:1

----- Context ------------------------------------------------------------------
1: (try 1 (throw (Exception. "hi")))
   ^--- hi
```

Question about the stack creation - I was thinking about introducing a `make-stack` function that takes the expression's meta and a boolean for special form and tacks on the `:ns` and `:file` meta, but I'm curious if this option has previously been eliminated to save the extra function call and conditional overhead. I figure it's easier to ask up front than to spend CI cycles on changes to a PR later.

**Comment by borkdude** [comment] 2022-04-16 20:59
An extra function call isn't a problem. Maybe you can make a micro-PR to show what you're planning to do.

**Comment by borkdude** [comment] 2022-04-17 15:13
@bobisageek Is the above merged PR sufficient to close this issue?

**Comment by bobisageek** [comment] 2022-04-17 16:46
I'd say it might be possible to create other scripts where context might be missing, but the PR is sufficient for the examples discussed, so I'd say we can close this and open a new issue if we identify another example.

**Closed** 2022-04-17 16:47 UTC
