### ISSUE TITLE
Command line parameters not being parsed by scripts, passing right through if Babashka has the same ones.

### ISSUE THREAD

**Issue by laseray** [babashka/babashka#1657] opened 2024-01-12 17:35 UTC
**version**

babashka v1.3.187

**platform**

Linux (Manjaro kernel 6.6.8-2)

**problem**

Command line parameters to Babashka scripts are no longer processed as in previous versions.

All the standard command line parameters that bb takes are passed right through to it and not captured for use by a script itself.

**repro**

Whatever bb expects just goes right through. For instance,  -h to get help goes right through to give bb help, not the help text of the script itself (that has already been set up and worked) because it never receives the parameter.  The same happens with other default parameters of bb.

The explanation given should be clear enough. You either get your specific action due to parsing the parameters as coded (as it functioned in the past) or you don't, and get bb's defaults for those parameters.

It seems the parsing of command line params for bb is operating ahead of the scripting code to capture them and divert them to other operations.

Scripts are using parse-opts of clojure.tools.cli to get *command-line-args*

**expected behavior**

Parameters should not pass right through if there is command line parsing done by the script to execute specific actions.

**Comment by borkdude** [comment] 2024-01-12 19:27
This is a duplicate of https://github.com/babashka/babashka/issues/1658 I think? Although you posted earlier, I've already mentioned the other one in a changelog.

I'll make a release shortly.

**Closed by borkdude** 2024-01-12 19:27 UTC

**Comment by laseray** [comment] 2024-01-13 00:13
Okay great.
