### ISSUE TITLE
defmacro with a defrecord inside fails to resolve classname

### ISSUE THREAD

**Issue by cldwalker** [babashka/babashka#1170] opened 2022-02-08 02:51 UTC
Hi @borkdude. I think this is a bug but if it's not supported, happy to change to a feature request

**version**

0.7.4

**platform**

osx

**problem**

While trying to use datalog-parser 0.1.9, I get the following error:

```
----- Error --------------------------------------------------------------------
Type:     clojure.lang.ExceptionInfo
Message:  Unable to resolve classname: Placeholder
Location: datalog/parser/type.cljc:39:13
Phase:    analysis

----- Context ------------------------------------------------------------------
35: ;; constant       = any non-variable data literal
36: ;; plain-symbol   = symbol that does not begin with "$" or "?"
37: ;; mapping-key    = key for mapping the result
38:
39: (deftrecord Placeholder [])
                ^--- Unable to resolve classname: Placeholder
```

[Here's the relevant source code](https://github.com/lambdaforge/datalog-parser/blob/02d193f397afc3f93da704e7c6c850b194f0e797/src/datalog/parser/type.cljc#L12-L39) that is failing

**repro**

```sh
bb --classpath $(clojure -Sdeps '{:deps {io.lambdaforge/datalog-parser {:mvn/version "0.1.9"}}}' -Spath) -e "(require '[datalog.parser])"
```

**expected behavior**

Able to load namespace without failure

**Comment by borkdude** [comment] 2022-02-08 09:50
@cldwalker I think this is a bug. When I insert the direct macroexpansion, then it works fine:

```
(clojure.core/defrecord Placeholder []
  datalog.parser.impl.proto/Traversable
  (-traversable? [___159__auto__] true)
  datalog.parser.impl.proto/ITraversable
  (-postwalk [this__160__auto__ f164]
    (clojure.core/-> (new Placeholder)
                     (clojure.core/vary-meta clojure.core/merge (clojure.core/meta this__160__auto__))))
  (-collect [___159__auto__ pred165 acc166] acc166) (-collect-vars [___159__auto__ acc166] acc166))
```

Needs more debugging.

**Comment by borkdude** [comment] 2022-02-08 09:57
I found this bug when trying to macroexpand `defrecord` but it's probably not the cause of this bug:

https://github.com/babashka/sci/issues/677

**Comment by borkdude** [comment] 2022-02-08 10:48
@cldwalker When I change the `deftrecord` macro to:

``` clojure
#?(:clj
   (defmacro deftrecord
     "Augment all parser records with default implementation of ITraversable"
     [tagname fields & rest]
     (let [[f pred acc]  (map gensym ["f" "pred" "acc"])
           walked-fields (map #(list `util/postwalk % f) fields) ]
       `(defrecord ~tagname ~fields
          p/Traversable
          (~'-traversable? [_#] true)
          p/ITraversable
          (~'-postwalk [this# ~f]
           (-> (~(symbol (str "->" tagname)) ~@walked-fields)
               (vary-meta merge (meta this#))))
          (~'-collect [_# ~pred ~acc]
           ~(reduce #(list `collect pred %2 %1) acc fields))
          (~'-collect-vars [_# ~acc]
           ~(reduce #(list `collect-vars %1 %2) acc fields))
          ~@rest))))
```

replacing `(new ~tagname)` with `~(symbol (str "->" tagname))`, then it works. SCI has problems resolving `(new Foo)` to a record apparently in this spot. I'll fix it soon, but hopefully this unblocked you for now.

**Comment by cldwalker** [comment] 2022-02-08 14:32
Thanks for the workaround and for looking into it ❤️

**Closed** 2022-02-08 22:55 UTC

**Comment by borkdude** [comment] 2022-02-08 22:56
@cldwalker Found the issue, it had to do with top level expressions and evaluation of `do` with macros returning `do`. Should be fixed now. Perhaps we could also add datalog parser to projects.md + libtests. PR welcome.
