### ISSUE TITLE
On MS-Windows, support execution of running commands without a filename extension with `shell` 

### ISSUE THREAD

**Issue by ikappaki** [babashka/babashka#1078] opened 2021-11-26 22:41 UTC
**Is your feature request related to a problem? Please describe.**

There are command line tools that are available on all major operating systems and can be simply invoked by their name. An example of such tool is `npm`. 

When writing tasks with babashka, authors usually call on the shell command to invoke the command they wish to execute. I find this akin as to invoking a command from the bash shell on Linux or the Command Prompt on MS-Windows.

Though, if we write a bb.edn  file to invoke, say,  the `npm` command on Linux with bb `shell` it will work, but the same will fail on MS-Windows with the following message

```
----- Error --------------------------------------------------------------------
Type:     java.io.IOException
Message:  Cannot run program "npm": CreateProcess error=2, The system cannot find the file specified
```

This is because the full filename of the `npm` file on MS-Windows is `npm.cmd`, and the `shell` command which is calling down to the standard java API and from there down to the Win32 [createProcess](https://docs.microsoft.com/en-gb/windows/win32/api/processthreadsapi/nf-processthreadsapi-createprocessw) function, only considers the `.exe` extension for a cmd supplied without an extension, as we did with the above.

Thus it is not possible to write cross platform code targeting tools that are considered to be cross platform (e.g. the `node.js` package executables,  which appear as `.cmd` files on MS-Windows).

**Describe the solution you'd like**
The `shell` command should behave as the Command Prompt on MS-Windows, using the same heuristics to figure out the correct filename to call when there is no extension supplied.

**Describe alternatives you've considered**

The bb.edn files have to be written with a conditional to explicitly consider the extension for MS-Windows. Thus taking npm as an example, it should be specified as `npm.cmd` for MS-Windows and just `npm` for every other OS, which I find too much for an author to consider, they might not even use MS-Windows. Things should just work as expected across platforms.

**Additional context**

Raised #1077 PR with a draft implementation of the above.

**Comment by borkdude** [comment] 2021-11-26 22:49
1) Are there any downsides to doing this automatically? Like, is there anything that could go wrong that cannot be undone if bb did this automatically and should it therefore be an option?

2) What is the correct order of resolving an executable on Windows? What if there are multiple alternatives: `foo.exe`, `foo.bat` and `foo.cmd`, which has priority? Are these the only valid executable names on Windows or can you basically execute any file with any extension using `Process` (or babashka.process) in Java (and should we therefore also consider the file without extension)?

3) Is there any prior art in the Java / Clojure space that solves this problem that we could look at? 

 4) I think it makes sense to have at least some utility function with the above logic in babashka.fs or babashka.process (or both?) that we could re-use in shell, if we were to do this automatically.

/cc @bobisageek

**Comment by ikappaki** [comment] 2021-11-26 23:03
> 1. Are there any downsides to doing this automatically? Like, is there anything that could go wrong that cannot be undone if bb did this automatically and should it therefore be an option?

I can't think of something at the moment, other than getting the heuristics wrong (and thus the extensive test coverage in the proposed implementation).

>     2. What is the correct order of resolving an executable on Windows? What if there are multiple alternatives: `foo.exe`, `foo.bat` and `foo.cmd`, which has priority? Are these the only valid executable names on Windows or can you basically execute any file with any extension using `Process` (or babashka.process) in Java (and should we therefore also consider the file without extension)?
 
There is this `PATHEXT` environment variable that determines the applicable extensions, for example  on my MS-Windows machine is

PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS

The actual logic to locate the extension is as follows (as taken from the proposed solution commentary). 

Given an absolute, relative or solo filename to a CMD with ENV-PATH and ENV-PATHEXT being the PATH and PATHEXT environment variables respectively:

```
  1. The extension of the CMD, if any.

  2. or if CMD is an absolute path, then it is the first item in
  ENV-PATHEXT list that when appended to CMD matches an existing file.

  2. or if CMD is an relative path, then it is the first item in
  ENV-PATHEXT list that when appended to CMD matches an existing file
  relative to the current working directory.

  3. or if CMD is just a solo filename, then it is the first item in
  ENV-PATHEXT list that when appended to CMD matches an existing file
  relative to the current working directory or relative to a path in
  the ENV-PATH list (iterated from first to last).
```

>     3. Is there any prior art in the Java / Clojure space that solves this problem that we could look at?

I couldn't find anything in my search, but will look again.

>     4. I think it makes sense to have at least some utility function with the above logic in babashka.fs or babashka.process (or both?) that we could re-use in shell, if we were to do this automatically.

Agreed, the proposed implementation used it as an auxilary fn in babashka.impl.tasks to support the `shell` fn, but is best to be placed somewhere else. `bababshka.fs` sounds like a better option.

Thanks


> 
> /cc @bobisageek

**Comment by bobisageek** [comment] 2021-11-27 02:32
After a little experimenting, I think there are a couple of points that might be interesting to think about.

- Sort of a small nitpick, but relying on whether the file name has a period in it to decide seems a tiny bit problematic in the case where a filename has a period, e.g. 'project.dev.cmd'. The Windows `where` command will find the script with the extension when searching 'project.dev', but it looks like the `ext?` binding would be true, meaning we'd return the path without the extension.
- I agree it would be nice to have `shell` act a bit more like the command prompt on Windows, or possibly more desirably, somewhat like the "run" dialog. However, PATHEXT would only partially achieve that.
As far as I know, PATHEXT includes things like `.vbs` and `.js` by default, which means that things like VBScript and MS JScript. My python install also puts `.py` into PATHEXT. In any case, there are (in general) extensions besides "batch scripts" in PATHEXT. From `cmd` or the "run" dialog, these behave "as expected" (invoking a usable 'interpreter'), but using `babashka.process` (or a `ProcessBuilder` or `Runtime/exec`) to execute one of these other file types leads to an error about the script not being "a valid Win32 application".

```shell
C:\testing_stuff>type ex1.py
print("abc")

C:\testing_stuff>ex1.py
abc

C:\testing_stuff>bb "(babashka.process/process [\"ex1.py\"] {:err :string})"
----- Error --------------------------------------------------------------------
Type:     java.io.IOException
Message:  Cannot run program "ex1.py": CreateProcess error=193, %1 is not a valid Win32 application
...
```

I think this leads to one of two follow-ups: either there needs to be additional work to decide what should be prepended to the command line (which I think makes things considerably more complex), or it has to be clear that although we're using PATHEXT to find the file, we're still not really executing 100% like `cmd` or the "run" dialog. So, with regard to 'executing things via `shell` without needing to specify the extension', it's not as comprehensive as the Windows built-in stuff, but somewhat more comprehensive than what comes with the JVM/Clojure built-ins - it's sort of a third set of capabilities that people need to know.

- I think a pattern that comes up quite a bit for shelling out is to use `cmd /c` or `bash -c` before the 'command line' in question (e.g. `cmd /c npm -h`). Just to throw out a wacky idea, I wonder if it would make sense to consider something that tacks a shell call on to the front of the command line, as a way of explicitly asking for `cmd` or `bash` (or other shell) semantics (whereas I feel like the whole PATHEXT lookup thing is sort of trying to re-implement a subset of the semantics).

- Finally, purely an opinion, but I think any work that comes out of this might make more sense in `babashka.process`, just because (at least in my mind) capabilities like finding executable things on a PATH are more specific to processes than filesystems. It feels like there's a good chance that if `shell` were made to "work better" (for almost any value of 'better') with Windows, it probably wouldn't take long before that improvement would be desirable in `babashka.process`.

**Comment by borkdude** [comment] 2021-11-27 11:08
> I agree it would be nice to have shell act a bit more like the command prompt on Windows

I must emphasize that the name `shell` does not mean that it is actually running or trying to emulate a shell. The name just comes from "shelling out", similar to the naming in `clojure.java.shell`. I'm not intending to support bash syntax or Windows-specific behaviours of `cmd.exe`, `Powershell` etc. 

However, making it easier to resolve an executable on Windows is a reasonable thing to support.

Proposal:
Let's add a function called `find-executables-on-path` that takes a list of configurable extensions to take into account, which on Windows defaults to  `["com", "exe", "bat", "cmd"]`, on linux/mac it defaults to `nil`. It returns a (lazy) list of all executables found on the path:

```
(path-executables "yarn" {:extensions ...})
```

Then there can be another function called `path-executable` which just returns the first one.

And then we can support an option in `babashka.process`: `path-executable true` which uses this function to resolve the binary. On unix this defaults to false since it's in general not necessary, but on Windows it defaults to true, _iff_ the program name (the first string argument to process) is a relative path and does not have an extension.

And then this is automatically supported in `shell` as well.

Sounds good @ikappaki @bobisageek ?

**Comment by borkdude** [comment] 2021-11-27 11:17
Perhaps we should add another function called `default-executable-resolver` which does nothing if the program name:

- contains directories
- is an absolute path
- so only when you provide a relative name without directories it calls `path-executable` _only on Windows_, else it just returns the argument

And then `default-executable-resolver` is the default option for all platforms, it just behaves in a platform-specific way.

**Comment by ikappaki** [comment] 2021-11-27 11:43
Hi @borkdude, this sounds good to me since it resolves the cross compatibility glitches on Windows. Thanks for clarifying the intention behind `shell`. I can try coding something up provided there are no further concerns.

 I suppose the `default-executable-resolver` is something we add in `babashka.process/*defaults*  as a new entry?

@bobisageek feedback was all up to the point, especially about the process fn not being able to invoke files with non standard extensions. 

Thanks

**Comment by borkdude** [comment] 2021-11-27 12:09
@ikappaki That makes sense!

**Comment by borkdude** [comment] 2021-11-27 15:12
@ikappaki Do you want to go ahead and make a PR or do you want me to do this? I was about to release a new version of bb but I can wait a bit more.

**Comment by ikappaki** [comment] 2021-11-27 15:18
> @ikappaki Do you want to go ahead and make a PR or do you want me to do this? I was about to release a new version of bb but I can wait a bit more.

Hi @borkdude, it'll be faster if you go ahead and implement the proposed please, it might take me to the beg of next week before I got something ready. due to limited availability over the next few days.

Thanks,

**Comment by borkdude** [comment] 2021-11-28 19:55
I started extending the `babashka.fs/which` function which already resolve an executable on the path. There I encountered the following:

``` clojure
user=> (slurp "C:\\Users\\borkdude\\scoop\\shims\\scoop")
"#!/bin/sh\npowershell.exe -noprofile -ex unrestricted \"C:\\Users\\borkdude\\scoop\\apps\\scoop\\current\\bin\\scoop.ps1\"  \"$@\"\r\n"
user=> (fs/which "scoop.exe")             
nil    
user=> (fs/which "scoop.bat") 
nil    
user=> (fs/which "scoop.cmd") 
#object[sun.nio.fs.WindowsPath 0x76889e60 "C:\\Users\\borkdude\\scoop\\shims\\scoop.cmd"]
```

I guess it's better to ignore executables found that are without extension as there can also be unix scripts on the path?

**Comment by borkdude** [comment] 2021-11-28 20:03
On fs master I "fixed" it:

```
user=> (require '[babashka.fs :as fs]) 
nil
user=> (fs/which "scoop")
#object[sun.nio.fs.WindowsPath 0x7c8f9c2e "C:\\Users\\borkdude\\scoop\\shims\\scoop.cmd"]
```

**Comment by borkdude** [comment] 2021-11-28 20:44
```
(deftest ^:windows windows-executable-resolver-test
  (when #'p/windows?
    (prn (-> @(p/process "java --version" {:out :string})
             :out))
    (prn (-> @(p/process ["java" "--version"] {:out :string})
             :out))))

C:\Temp\process>deps -M:test -v babashka.process-test/windows-executable-resolver-test

Running tests in #{"test"}

Testing babashka.process-test
"openjdk 11.0.7 2020-04-14\r\nOpenJDK Runtime Environment 18.9 (build 11.0.7+10)\r\nOpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode)\r\n"
"openjdk 11.0.7 2020-04-14\r\nOpenJDK Runtime Environment 18.9 (build 11.0.7+10)\r\nOpenJDK 64-Bit Server VM 18.9 (build 11.0.7+10, mixed mode)\r\n"
```

**Comment by borkdude** [comment] 2021-11-28 20:46
Pushed to master. Should also work in shell. Please test, also your existing tasks, I hope I haven't introduced any regressions. @ikappaki @bobisageek.

**Comment by borkdude** [comment] 2021-11-28 22:07
Binary for testing: https://ci.appveyor.com/api/buildjobs/4wohqob8t5mkruvw/artifacts/babashka-0.6.6-SNAPSHOT-windows-amd64.zip

**Comment by ikappaki** [comment] 2021-11-28 23:14
Hi @borkdude,

starting to look really good.! A couple of comments:

1.  `fs/which` newly found paths need to be strings, not `Path`s, the `shell` command will fail otherwise try to use the Path as a string.
2. It does not seem it support commands with multiple dots in their filenames, as per @bobisageek comment earlier in this thread. So for example if the executable name is `io.dev.bat` and we `shell` for `io.dev` it will fail to locate it. I suppose we still want to support this case?

Not sure how what is the best way to share big chunks of code, and thus I've created a gist with the `fs.cljc` fix for point 1 above, and a `tasks_test.clj` test playground to demonstrate point 2, trying out different path configurations with batch files in a temp directory. The latter can be also a candidate for checking in if you think it worths the trouble (it's currently a quick hack and needs a face lift, perhaps .bat files can echo their full path to identify themselves when we run them, so we can check the correct executable was invoked).

https://gist.github.com/ikappaki/ad3a71b235c119dbb920166fd0bc436f#file-fs-cljc-L27

I'll hope to find some time on Monday to test the binary.

Thanks for looking into this!

**Comment by borkdude** [comment] 2021-11-29 10:09
To point 1: `fs/which`, like almost any other function in `fs` returns either a Path, File or String. If you care about the specific type you should convert with either `fs/path`, `fs/file` or `str`. This is what `babashka.process` does.

To point 2: This has been addressed on master now. I'll post a new binary link later.

**Comment by borkdude** [comment] 2021-11-29 10:25
New binary: https://ci.appveyor.com/api/buildjobs/2wmo8u8lpww4045r/artifacts/babashka-0.6.6-SNAPSHOT-windows-amd64.zip

**Comment by borkdude** [comment] 2021-11-29 11:34
I didn't want to delay the release so I released this in 0.6.6, but if we find any bugs related to this I will do a follow up release.

**Comment by borkdude** [comment] 2021-11-29 11:34
Let's create a new issue when we find any new bugs.

**Closed by borkdude** 2021-11-29 11:34 UTC
Labels: windows

**Comment by ikappaki** [comment] 2021-11-29 20:43
Thanks a lot for the quick turn around, looks great! I've got another, but extreme, case failing, will raise an issue for it.

**Comment by borkdude** [comment] 2021-11-29 21:12
@ikappaki extreme case? Omg, don't keep me in suspense...

**Comment by ikappaki** [comment] 2021-11-29 21:21
> @ikappaki extreme case? Omg, don't keep me in suspense...

#1083, the `io.bat.bat` case, nothing serious a contrived corner case that we might need to fix. I'm more worried about the `fs\which` case I've just noticed with `java.exe` and piggybacked on the issue.
