### ISSUE TITLE
Build Apple M1 binary on CI?

### ISSUE THREAD

**Issue by johnjelinek** [babashka/babashka#1271] opened 2022-05-19 23:01 UTC
**Is your feature request related to a problem? Please describe.**
```shell
asdf install babashka latest
```
This is [failing at the moment](https://github.com/fredZen/asdf-babashka/issues/3) because there isn't an arm64 release.

**Describe the solution you'd like**
Please add a release for arm64.

**Describe alternatives you've considered**
A [PR](https://github.com/fredZen/asdf-babashka/pull/4) that forces rosetta emulation, but that's not great.

**Additional context**
On an M1 mac.

**Comment by borkdude** [comment] 2022-05-20 07:11
This is a duplicate of #1067. The summary:

You can build your own m1 binary using these instructions:

https://github.com/babashka/babashka/wiki/Compiling-for-M1

However, since there is no free CI available on which we can build bb for m1, we can't reliably distribute this binary.

I am using babashka amd64 all the time on my M1 Macbook Air and it works without any configuration, as long as you have Rosetta2 Installed, so that should be the way to go until we get the M1 binary from CI.

The same is true for clj-kondo.

**Comment by borkdude** [comment] 2022-05-20 07:13
I'll keep the issue open until we have M1 CI (which could potentially take a long time).

**Comment by borkdude** [comment] 2022-05-20 11:14
@thiagokokada made me aware that nix provides arm binaries:

https://github.com/babashka/babashka#nix

**Comment by johnjelinek** [comment] 2022-05-20 14:14
That's nice. Also looks like there's brand new support for cross compiling for m1: https://github.com/oracle/graal/issues/2666#issuecomment-1131855076

**Comment by borkdude** [comment] 2022-05-20 14:18
@johnjelinek AFAIK native-image does not support cross-compiling. Where do you see that?

**Comment by johnjelinek** [comment] 2022-05-20 14:22
I miss typed and edited my comment to remove reference to cross-compiling.

**Comment by borkdude** [comment] 2022-05-20 14:23
I wish they did btw :)

**Comment by introom** [comment] 2022-05-22 13:15
babashka (with rosetta) works fine on my m1 until I use fish completion and notices the noticeable delay with `bb tasks` for fish shell completion.

**Comment by borkdude** [comment] 2022-07-03 11:43
The M1 binary has been available for a while now.

**Closed by borkdude** 2022-07-03 11:43 UTC
